### ISSUE TITLE
Future of Repository

### ISSUE THREAD

**Issue by BDEvan5** [f1tenth/f1tenth_baselines#1]
Hello

I was wondering what the future plans for the (currently empty) repo are?
Is there is a timeline for the authors of the paper to upload their baseline solutions?

Is the aim of the repo just for the baselines presented in the paper, or is it a platform for people to compare their solutions?
I think that it would be a useful place for different researchers to compare their work.

Regards
Benjamin

**Comment by hzheng40** [comment]
The plan is to have a benchmark/leaderboard similar to the one we see [here](https://www.nuscenes.org/object-detection?externalData=all&mapData=all&modalities=Any). We currently have a small team working on making this happen as part of the online virtual racing submission platform.
As for the baseline methods we mentioned in the paper, I'll have to collect and convert the solutions since the gym was overhauled. I can't really guarantee any timeline (busy year) but things will be slowly added.
